In [3]:
import pandas as pd

In [4]:
df=pd.read_csv('Crimes_-_2001_to_present.csv')

In [23]:
df.head(10)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,4700982,HM212393,03/03/2006 10:40:00 PM,0000X W 95TH ST,1811,NARCOTICS,POSS: CANNABIS 30GMS OR LESS,CTA TRAIN,True,False,...,21.0,49.0,18,1177762.0,1841949.0,2006,04/15/2016 08:55:02 AM,41.721627,-87.624485,"(41.721627204, -87.624485177)"
1,4700983,HM300030,01/01/2006 12:00:00 PM,049XX S HOYNE AVE,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,...,16.0,61.0,06,1163199.0,1871730.0,2006,04/15/2016 08:55:02 AM,41.803667,-87.676995,"(41.803667166, -87.676994658)"
2,4700984,HM300880,04/19/2006 09:20:00 PM,0000X W 95TH ST,0460,BATTERY,SIMPLE,CTA GARAGE / OTHER PROPERTY,False,False,...,21.0,49.0,08B,1177762.0,1841949.0,2006,04/15/2016 08:55:02 AM,41.721627,-87.624485,"(41.721627204, -87.624485177)"
3,4700985,HM304274,04/21/2006 01:45:00 PM,104XX S AVENUE L,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,...,10.0,52.0,14,1201838.0,1836252.0,2006,04/15/2016 08:55:02 AM,41.705416,-87.536494,"(41.70541635, -87.536493961)"
4,4700986,HM305728,04/22/2006 12:00:00 AM,082XX S PRAIRIE AVE,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,...,6.0,44.0,07,1179463.0,1850527.0,2006,04/15/2016 08:55:02 AM,41.745128,-87.617994,"(41.745127679, -87.617993623)"
5,4700987,HM301529,04/19/2006 08:00:00 PM,040XX S WELLS ST,0460,BATTERY,SIMPLE,RESIDENCE,False,False,...,3.0,37.0,08B,1175323.0,1877918.0,2006,04/15/2016 08:55:02 AM,41.820385,-87.632345,"(41.820384954, -87.632344948)"
6,4700988,HM302514,04/20/2006 05:55:26 PM,002XX S WABASH AVE,1210,DECEPTIVE PRACTICE,THEFT OF LABOR/SERVICES,CTA PLATFORM,True,False,...,42.0,32.0,11,1176845.0,1899360.0,2006,04/15/2016 08:55:02 AM,41.879189,-87.626114,"(41.879189117, -87.626113803)"
7,4700990,HM302465,04/19/2006 10:00:00 AM,114XX S CHURCH ST,0820,THEFT,$500 AND UNDER,STREET,False,False,...,19.0,75.0,06,1165850.0,1828882.0,2006,04/15/2016 08:55:02 AM,41.686030,-87.668486,"(41.68603007, -87.668486254)"
8,4700991,HM212402,03/04/2006 12:07:00 AM,047XX S ADA ST,2022,NARCOTICS,POSS: COCAINE,STREET,True,False,...,3.0,61.0,18,1168124.0,1873431.0,2006,04/15/2016 08:55:02 AM,41.808230,-87.658883,"(41.808230277, -87.658883267)"
9,4700992,HM300972,04/19/2006 08:30:00 PM,083XX S MARYLAND AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,...,8.0,44.0,08B,1183341.0,1849955.0,2006,04/15/2016 08:55:02 AM,41.743469,-87.603802,"(41.743468705, -87.603801924)"

In [12]:
a=df['Date']
b=[{'date':' ','time':' ', 'ampm':' '} for i in range(len(a))]

In [16]:
for i in range(len(a)):
    c=a[i].split(' ')
    b[i]['date']=c[0]
    b[i]['time']=c[1]
    b[i]['ampm']=c[2]

In [31]:
year=[]
month=[]
date=[]
hours=[]
mins=[]
for i in b:
    x=map(int,i['date'].split('/'))
    y=map(int,i['time'].split(':'))
    month.append(x[0])
    date.append(x[1])
    year.append(x[2])
    mins.append(y[1])
    if i['ampm']=='PM':
        if y[0]==12:
            y[0]=0
        hours.append((y[0]+12))
    else:
        hours.append(y[0]%12)

In [32]:
print year
print month
print date
print hours
print mins

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

In [33]:
df['Year']=year
df['Month']=month
df['Date_value']=date
df['Hour']=hours
df['Minutes']=mins

In [36]:
df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,Month,Date_value,Hour,Minutes
0,4700982,HM212393,03/03/2006 10:40:00 PM,0000X W 95TH ST,1811,NARCOTICS,POSS: CANNABIS 30GMS OR LESS,CTA TRAIN,True,False,...,1841949.0,2006,04/15/2016 08:55:02 AM,41.721627,-87.624485,"(41.721627204, -87.624485177)",3,3,22,40
1,4700983,HM300030,01/01/2006 12:00:00 PM,049XX S HOYNE AVE,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,...,1871730.0,2006,04/15/2016 08:55:02 AM,41.803667,-87.676995,"(41.803667166, -87.676994658)",1,1,12,0
2,4700984,HM300880,04/19/2006 09:20:00 PM,0000X W 95TH ST,0460,BATTERY,SIMPLE,CTA GARAGE / OTHER PROPERTY,False,False,...,1841949.0,2006,04/15/2016 08:55:02 AM,41.721627,-87.624485,"(41.721627204, -87.624485177)",4,19,21,20
3,4700985,HM304274,04/21/2006 01:45:00 PM,104XX S AVENUE L,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,...,1836252.0,2006,04/15/2016 08:55:02 AM,41.705416,-87.536494,"(41.70541635, -87.536493961)",4,21,13,45
4,4700986,HM305728,04/22/2006 12:00:00 AM,082XX S PRAIRIE AVE,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,...,1850527.0,2006,04/15/2016 08:55:02 AM,41.745128,-87.617994,"(41.745127679, -87.617993623)",4,22,0,0

In [37]:
df.to_csv('chicago_updated.csv')

In [ ]:
crime_count={i:0 for i in set(df['Primary Type'])}
year_count={i:0 for i in set(df['Year'])}
time_count={i:0 for i in set(df['Hour'])}
location= {i:0 for i in set(df['Location Description'])}
community= {i:0 for i in set(df['Community Area'])}

In [49]:
for i in range(len(a[1:5])):
    crime_count[df.loc[i, 'Primary Type']]+=1
    year_count[df.loc[i,'Year']]+=1
    time_count[df.loc[i,'Hour']]+=1
    location[df.loc[i,'Location']]+=1
    community[df.loc[i,'Community Area']]+=1

In [ ]:
location